### PR TITLE
update lodash dependencies

### PR DESCRIPTION
**Pull request by brekk**
Hi there,

Updated `lodash` to 4.17.4

Please let me know if there are additional steps I should take here.

Thanks,

Brekk

### CODE REVIEW

**Comment by finneganh** [comment]
Not something I’m interested in right now. If this package ever needs a large overhaul (like switching to the 2.0 API for react-transition-group) I’d probably tackle other dependency updates at that point.

**Comment by brekk** [comment]
@finneganh ok, but this is a blocking issue for me. thanks for your time.

**Comment by finneganh** [comment]
Your problem likely lies elsewhere. With a well-configured npm and resource bundler, the version of lodash that velocity-react uses should not impact any uses of different versions of lodash in your app.

Or feel free to just use your fork. This repo doesn't change much.

**Comment by turadg** [comment]
> With a well-configured npm and resource bundler, the version of lodash that velocity-react uses should not impact any uses of different versions of lodash in your app.

True, wrt to runtime. The cost of not upgrading Lodash is that it causes the build to contain Lodash v3 and Lodash v4.

**Comment by STRML** [comment]
@finneganh FWIW this is now the fourth PR that's been rejected to update Lodash to v4, and we personally have to add this to our storybook webpack config to work around the use of v3 here:

```js
  // hack to work around velocity-react using lodash 3, which trips some kind of webpack bug
  out.resolve.modules.push("node_modules/velocity-react/node_modules");
```

It would be really nice if you would just merge one.

**Pull request closed without merging**
